version: '3.4'

services:
  productservice.api:
    image: ${DOCKER_REGISTRY-}productserviceapi
    build:
      context: .
      dockerfile: ProductService.API/Dockerfile

  mongodb_container_product:
    image: mongo:latest
    container_name: product-db
    ports:
      - 27017:27017

  saleservice.api:
    image: ${DOCKER_REGISTRY-}saleserviceapi
    build:
      context: .
      dockerfile: SaleService.API/Dockerfile
  
  mongodb_container_sale:
    image: mongo:latest
    container_name: sale-db
    ports: 
      - 27018:27017

